# Generated by Django 5.1.3 on 2025-03-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationAnalysis',
        ),
    ]
