# Generated by Django 5.1.3 on 2025-02-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(default='Thank You'),
            preserve_default=False,
        ),
    ]
