# Generated by Django 5.1.3 on 2025-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_donation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donationMethod',
            field=models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('imepay', 'ImePay')], default='esewa', max_length=20),
            preserve_default=False,
        ),
    ]
